FirstProject/Models/Shift.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set; }
    }
}

FirstProject/Controllers/ShiftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using FirstProject.Models;

namespace FirstProject.Controllers
{
    public class ShiftController : Controller
    {
        ShiftBL employeeShiftBL = new ShiftBL();
        // GET: Shift
        public ActionResult Index()
        {
            return View();
        }
         public ActionResult GetShifts()
        {
             var result = employeeShiftBL.GetShifts();
             ViewBag.ShiftsData = result;


             return checkCounterOfActionsAndReturnAction(View("Shifts"));
         }

        public ActionResult EditEmployee(int empID)
        {
           
            string returnURL = "/employee/EditEmployee?empID=" + empID.ToString();

            return checkCounterOfActionsAndReturnAction(Redirect(returnURL));

           
        }

        public ActionResult AddShiftToEmployee(int empID)
        {
            string returnURL = "/employee/AddShiftToEmployee?empID=" + empID.ToString();

            return checkCounterOfActionsAndReturnAction(Redirect(returnURL));
        }

        public ActionResult GetEmpForShift(int shID)
        {
            var emp = employeeShiftBL.GetEmpForShift(shID);
            ViewBag.empData = emp;
            
            return checkCounterOfActionsAndReturnAction(View("EmployeesForShift"));
        }
        
        public ActionResult checkCounterOfActionsAndReturnAction(ActionResult action)
        {
            int counter = (int)Session["numOfActions"];
            counter--;
            Session["numOfActions"] = counter;

            if (counter != 0)
            {
                return action;
            }
            else
            {
                return Redirect("/login/Logout");
            }
        }



    }
}

FirstProject/Views/Shift/EmployeesForShift.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EmployeesForShift</title>
</head>
<body>
    <div>
        <h3>Hello @Session["userFullName"]</h3>
        <a href="/login/Logout">Logout</a> <br /> <br />
        <h1>List of Employees for the Shift</h1>

        @foreach (var emp in ViewBag.empData)
        {
            <ul>
                <li><a href="@Url.Action( "EditEmployee", "Shift", new { empid = emp.ID })">@emp.FName </a></li>

                <li style="list-style-type: none">@Html.ActionLink("Add Shift", "AddShiftToEmployee", new { empID = @emp.ID })</li>
            </ul>

        }


    </div>
</body>
</html>

FirstProject/Views/Shift/Shifts.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Shifts</title>
</head>
<body>
    <h3>Hello @Session["userFullName"]</h3>
    <a href="/login/Logout">Logout</a> <br /> <br />

    <h1>Employees Shifts Table</h1>

    <div>
        <table border="1">

            <tr><th>Date</th><th>Start Time</th><th>End Time</th><th>Show Employees</th></tr>

            @foreach (var shift in ViewBag.ShiftsData)
            {

                <tr>
                    <td>@shift.ShiftDate</td>
                    <td>@shift.StartTime</td>
                    <td>@shift.EndTime</td>


                    <td>@Html.ActionLink("Show Employees", "GetEmpForShift", new { shID = @shift.ShiftID })</td>

                </tr>
            }
        </table>

    </div>

</body>
        </html>